#!/usr/bin/env bash
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    
    
    
# install youcompleteme for supported language
# https://github.com/ycm-core/YouCompleteMe#macos
